// NOTE: This is generated by `w3 codegen`, DO NOT MODIFY

export const schema = `
type Query implements ApiResolver_Query {
  tryResolveUri(
    authority: String!
    path: String!
  ): ApiResolver_MaybeUriOrManifest

  getFile(
    path: String!
  ): Bytes # TODO: https://github.com/Web3-API/prototype/issues/100
}
`